Updated menu
Updated menu

diff --git a/amigapi b/amigapi
--- a/amigapi
+++ b/amigapi
@@ -67,11 +67,19 @@ calc_wt_size() {
 
 do_about() {
     whiptail --msgbox "\
-This tool provides an easy way to automatically
-configure a stock Minibian installation as an
-Amiga emulator machine. The system will boot
-directly into UAE, but a few additional tools
-will also be installed.\
+This tool provides an easy way to automatically \
+configure a stock Minibian installation as an \
+Amiga emulator machine. 
+After AmigaPi is installed, the system will boot \
+directly into UAE as fast as possible. \
+Additionally, a few additional tools (like a File Manager) \
+will also be installed.
+
+You can always re-run this tool to perform any of the \
+available functions.
+
+Created by Dimitris Panokostas.
+Visit http://blitterstudio.com/amigapi/ for the latest in this project.
 " 20 70 1
 }
 
@@ -630,13 +638,42 @@ do_internationalisation_menu() {
   fi
 }
 
-do_advanced_menu() {
-  FUN=$(whiptail --title "Raspberry Pi Software Configuration Tool (raspi-config)" --menu "Advanced Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
+do_configure_menu() {
+  FUN=$(whiptail --title "Raspberry Pi Software Configuration Tool (AmigaPi)" --menu "Configure System" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
+    "A1 WiFi" "Enable WiFi, asking for your SSID and Password" \
+	"A2 Internationalisation" "Set up language and regional settings to match your location" \
+    "A3 Hostname" "Set the visible name for this Pi on a network" \
+    "A4 SSH" "Enable/Disable remote command line access to your Pi using SSH" \
+    "A5 Audio" "Force audio out through HDMI or 3.5mm jack" \
+	"A6 Video" "Configure HDMI video options" \
+    "A0 Overclock" "Configure overclocking for your Pi" \
+    3>&1 1>&2 2>&3)
+  RET=$?
+  if [ $RET -eq 1 ]; then
+    return 0
+  elif [ $RET -eq 0 ]; then
+    case "$FUN" in
+      A1\ *) do_wifi_setup ;;
+	  A2\ *) do_internationalisation_menu ;;
+      A3\ *) do_hostname ;;
+      A4\ *) do_ssh ;;
+      A5\ *) do_audio ;;
+	  A6\ *) do_video_menu ;;
+      A0\ *) do_overclock ;;
+      *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
+    esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
+  fi
+}
+
+do_video_menu() {
+FUN=$(whiptail --title "Raspberry Pi Software Configuration Tool (AmigaPi)" --menu "Video Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
     "A1 Overscan" "You may need to configure overscan if black bars are present on display" \
-    "A2 Hostname" "Set the visible name for this Pi on a network" \
-    "A3 SSH" "Enable/Disable remote command line access to your Pi using SSH" \
-    "A4 Audio" "Force audio out through HDMI or 3.5mm jack" \
-    "A5 Overclock" "Configure overclocking for your Pi" \
+	"A2 HDMI Safe mode" "Enables maximum HDMI compatibility" \
+    "A3 Hostname" "Set the visible name for this Pi on a network" \
+    "A4 SSH" "Enable/Disable remote command line access to your Pi using SSH" \
+    "A5 Audio" "Force audio out through HDMI or 3.5mm jack" \
+	"A6 Overscan" "You may need to configure overscan if black bars are present on display" \
+    "A0 Overclock" "Configure overclocking for your Pi" \
     3>&1 1>&2 2>&3)
   RET=$?
   if [ $RET -eq 1 ]; then
@@ -644,10 +681,12 @@ do_advanced_menu() {
   elif [ $RET -eq 0 ]; then
     case "$FUN" in
       A1\ *) do_overscan ;;
-      A2\ *) do_hostname ;;
-      A3\ *) do_ssh ;;
-      A4\ *) do_audio ;;
-      A5\ *) do_overclock ;;
+	  A2\ *) do_hdmi_safe ;;
+      A3\ *) do_hostname ;;
+      A4\ *) do_ssh ;;
+      A5\ *) do_audio ;;
+	  A6\ *) do_overscan ;;
+      A0\ *) do_overclock ;;
       *) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
     esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
   fi
@@ -764,7 +803,7 @@ do_wifi_setup() {
   if [ $(dpkg-query -W -f='${Status}\n' wpasupplicant | grep -c "ok installed") -eq 0 ];
   then
     echo "Required package wpasupplicant not found. Setting up wpasupplicant..."
-    apt-get -y update && apt-get -y install wpasupplicant crda firmware-brcm80211 pi-bluetooth
+    apt-get -y update && apt-get -y install wpasupplicant crda firmware-brcm80211
 	# Configure WiFi
     # TODO This needs to check if the wlan0 is already present first
     cat <<EOF >> /etc/network/interfaces
@@ -813,6 +852,16 @@ to make changes to your WiFi configuration.\
   fi	
 }
 
+do_open_mc() {
+  if [ $(dpkg-query -W -f='${Status}\n' mc | grep -c "ok installed") -eq 0 ];
+  then
+    echo "Required package mc not found. Setting up mc..."
+    apt-get -y update && apt-get -y install mc
+  fi
+  
+  mc
+}
+
 do_reboot() {
   reboot now
 }
@@ -830,7 +879,6 @@ fi
 # Interactive use loop
 #
 if [ "$INTERACTIVE" = True ]; then
-  echo Checking for whiptail:
   if [ $(dpkg-query -W -f='${Status}\n' whiptail | grep -c "ok installed") -eq 0 ];
   then
     echo "Package whiptail not installed. Setting up whiptail..."
@@ -846,12 +894,11 @@ if [ "$INTERACTIVE" = True ]; then
   calc_wt_size
   while true; do
     FUN=$(whiptail --title "AmigaPi Software Configuration Tool" --menu "Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
-      "1 Expand Filesystem" "Ensures that all of the SD card storage is available to the OS" \
+      "1 Expand Filesystem" "Ensures that all of the SD card storage is available" \
       "2 Upgrade System" "Upgrade all installed packages to the latest version" \
-      "3 Setup AmigaPi (autostart)" "Installs and configures system to auto-boot in UAE" \
-      "4 Setup WiFi" "Installs and enables WiFi, asking for your SSID and Password" \
-      "5 Internationalisation Options" "Set up language and regional settings to match your location" \
-      "6 Advanced Options" "Configure advanced settings" \
+      "3 Setup AmigaPi" "Installs and configures system to auto-boot in UAE" \
+      "4 Configure System" "Configure various system options" \
+      "5 File Manager" "Open Midnight Commander to manage your files" \
       "8 Reboot" "Reboot the system" \
 	  "9 Shutdown" "Shutdown the system" \
 	  "0 About AmigaPi" "Information about this configuration tool" \
@@ -864,9 +911,8 @@ if [ "$INTERACTIVE" = True ]; then
         1\ *) do_expand_rootfs ;;
         2\ *) do_update ;;
         3\ *) do_amigapi_setup ;;
-        4\ *) do_wifi_setup ;;
-        5\ *) do_internationalisation_menu ;;
-        6\ *) do_advanced_menu ;;
+        4\ *) do_configure_menu ;;
+        5\ *) do_open_mc ;;
 		8\ *) do_reboot ;;
 		9\ *) do_shutdown ;;
         0\ *) do_about ;;
